version: '2'

services:

  airbnbcollector:
    build: .
    container_name: airbnbcollector
    depends_on:
      - postgresql
    volumes:       
      - ./docker/configs/:/collector/configs/
    command: tail -f /dev/null
    environment:
      USER: docker

  postgresql:
    image: mdillon/postgis:10-alpine
    container_name: airbnbcollector-db
    restart: always
    volumes:  
      - ./postgresql/:/sql/
      - ./docker/scripts:/docker-entrypoint-initdb.d/  
    environment:
      POSTGRES_PASSWORD: airbnb
      POSTGRES_USER: airbnb
